//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.01 at 01:27:13 PM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fowobi.com/spring/soap/api/bookservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fowobi.spring.soap.api.bookservice;
